name: Build
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - name: Build geosite
        id: build
        env:
          NO_SKIP: true
        run: |
          go run -v .
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: geosite.db
          path: geosite.db
